version: '3.7'
services:
  build:
    image: docker.pkg.github.com/falgon/roki-web/roki-web-env:latest
    container_name: roki-web-build-ghpr
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
    ports:
      - "8888:8888"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './site build --preview'
    deploy:
      resources:
        limits:
          memory: 4G
  preview:
    image: docker.pkg.github.com/falgon/roki-web/roki-web-env:latest
    container_name: roki-web-preview-ghpr
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
    ports:
      - "8888:8888"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './site watch --preview --port 8888 --host 0.0.0.0'
    deploy:
      resources:
        limits:
          memory: 4G
  spa:
    image: docker.pkg.github.com/falgon/roki-web/roki-web-env:latest
    container_name: roki-web-spa-ghpr
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
      - "../.github:/home/rw-c/bin/.github"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './spa yaml -d ${DATE:-""} -b ${BRANCH_NAME:-""} -y'
  clean:
    image: docker.pkg.github.com/falgon/roki-web/roki-web-env:latest
    container_name: roki-web-clean-ghpr
    tty: true
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './site clean'
  dev:
    image: docker.pkg.github.com/falgon/roki-web/roki-web-dev:latest
    container_name: roki-web-dev-ghpr
    tty: true
    volumes:
      - "../:/home/rw-dev/src"
    ports:
      - "8888:8888"
    working_dir: /home/rw-dev/src
    build:
      context: ../
      dockerfile: ./docker/dev/Dockerfile
    deploy:
      resources:
        limits:
          memory: 4G
