version: '3.7'
services:
  build:
    image: $ROKI_WEB_ENV_IMAGE_NAME:$ROKI_WEB_ENV_IMAGE_TAG
    container_name: roki-web-build
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
    ports:
      - "8888:8888"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './site build --preview'
  preview:
    image: $ROKI_WEB_ENV_IMAGE_NAME:$ROKI_WEB_ENV_IMAGE_TAG
    container_name: roki-web-preview
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
    ports:
      - "8888:8888"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './site watch --preview --port 8888 --host 0.0.0.0'
  spa:
    image: $ROKI_WEB_ENV_IMAGE_NAME:$ROKI_WEB_ENV_IMAGE_TAG
    container_name: roki-web-spa
    tty: true
    volumes:
      - "../contents:/home/rw-c/bin/contents"
      - "../.github:/home/rw-c/bin/.github"
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './spa yaml -d ${DATE:-""} -b ${BRANCH_NAME:-""} -y'
  clean:
    image: $ROKI_WEB_ENV_IMAGE_NAME:$ROKI_WEB_ENV_IMAGE_TAG
    container_name: roki-web-clean
    tty: true
    working_dir: /home/rw-c/bin
    build:
      context: ../
      dockerfile: ./docker/contents/Dockerfile
    command: /bin/bash -c './site clean'
  dev:
    image: $ROKI_WEB_DEV_IMAGE_NAME:$ROKI_WEB_DEV_IMAGE_TAG
    container_name: roki-web-dev
    tty: true
    volumes:
      - "../:/home/rw-dev/src"
    ports:
      - "8888:8888"
    working_dir: /home/rw-dev/src
    build:
      context: ../
      dockerfile: ./docker/dev/Dockerfile
