name: manually-gh-registry
on:
  workflow_dispatch:
    inputs:
      to_push:
        description: 'Push the built containers'
        required: true
        default: false
        type: boolean
      enable_notify:
        description: 'Send notification after image build'
        required: true
        default: true
        type: boolean
  push:
    branches: [master]
    tags:
      - v*
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
jobs:
  setup:
    runs-on: ubuntu-20.04
    if: github.repository == 'falgon/roki-web'
    outputs:
      img_tag: ${{ steps.img_tag_step.outputs.name }}
      env_img_name: ${{ steps.env_img_step.outputs.name }}
      dev_img_name: ${{ steps.dev_img_step.outputs.name }}
      env_gh_registry: ${{ steps.env_registry_step.outputs.name }}
      dev_gh_registry: ${{ steps.dev_registry_step.outputs.name }}
      to_push: ${{ steps.to_push_step.outputs.flag }}
      enable_notify: ${{ steps.enable_notify_step.outputs.flag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup environment variables
      run: |
        ENV_IMAGE_NAME=$(cat ./docker/.env | grep ROKI_WEB_ENV_IMAGE_NAME | cut -f2 -d=)
        DEV_IMAGE_NAME=$(cat ./docker/.env | grep ROKI_WEB_DEV_IMAGE_NAME | cut -f2 -d=)
        echo "ENV_IMAGE_NAME=$ENV_IMAGE_NAME" >> $GITHUB_ENV
        echo "DEV_IMAGE_NAME=$DEV_IMAGE_NAME" >> $GITHUB_ENV
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" = "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        IMAGE_TAG=$(test $VERSION = master && echo latest || echo $VERSION)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "ENV_GH_REGISTRY=docker.pkg.github.com/${{ github.repository }}/$(echo $ENV_IMAGE_NAME | cut -f2 -d/):$IMAGE_TAG" >> $GITHUB_ENV
        echo "DEV_GH_REGISTRY=docker.pkg.github.com/${{ github.repository }}/$(echo $DEV_IMAGE_NAME | cut -f2 -d/):$IMAGE_TAG" >> $GITHUB_ENV
        [[ "${{ github.event_name }}" = "push" ]] && TO_PUSH=true || TO_PUSH=${{ github.event.inputs.to_push }}
        echo "TO_PUSH=$TO_PUSH" >> $GITHUB_ENV
        [[ "${{ github.event_name }}" = "push" ]] && ENABLE_NOTIFY=false || ENABLE_NOTIFY=${{ github.event.inputs.enable_notify }}
        echo "ENABLE_NOTIFY=$ENABLE_NOTIFY" >> $GITHUB_ENV
    - name: Set the image tag outputs
      id: img_tag_step
      run: echo "::set-output name=name::$IMAGE_TAG"
    - name: Set env image outputs
      if: ${{ env.TO_PUSH == 'true' }}
      id: env_img_step
      run: echo "::set-output name=name::$ENV_IMAGE_NAME"
    - name: Set dev image outputs
      if: ${{ env.TO_PUSH == 'true' }}
      id: dev_img_step
      run: echo "::set-output name=name::$DEV_IMAGE_NAME"
    - name: Set env registry outputs
      if: ${{ env.TO_PUSH == 'true' }}
      id: env_registry_step
      run: echo "::set-output name=name::$ENV_GH_REGISTRY"
    - name: Set dev registry outputs
      if: ${{ env.TO_PUSH == 'true' }}
      id: dev_registry_step
      run: echo "::set-output name=name::$DEV_GH_REGISTRY"
    - name: Set to_push flag outputs
      id: to_push_step
      run: echo "::set-output name=flag::$TO_PUSH"
    - name: Set enable_notify flag outputs
      id: enable_notify_step
      run: echo "::set-output name=flag::$ENABLE_NOTIFY"
  build-env-image:
    runs-on: ubuntu-20.04
    needs: setup
    if: github.repository == 'falgon/roki-web'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the env image
      shell: bash
      run: |
        ROKI_WEB_ENV_IMAGE_TAG=${{ needs.setup.outputs.img_tag }} ROKI_WEB_DEV_IMAGE_TAG=${{ needs.setup.outputs.img_tag }} pushd ./docker && \
          docker-compose build --no-cache preview; \
        popd
    - name: Save images with tar
      if: ${{ needs.setup.outputs.to_push == 'true' }}
      run: docker save ${{ needs.setup.outputs.env_img_name }} > /tmp/env_img.tar
    - name: Upload the env image
      if: ${{ needs.setup.outputs.to_push == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: env_img
        path: /tmp/env_img.tar
  build-dev-image:
    runs-on: ubuntu-20.04
    needs: setup
    if: github.repository == 'falgon/roki-web'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the dev image
      shell: bash
      run: |
        ROKI_WEB_ENV_IMAGE_TAG=${{ needs.setup.outputs.img_tag }} ROKI_WEB_DEV_IMAGE_TAG=${{ needs.setup.outputs.img_tag }} pushd ./docker && \
          docker-compose build --no-cache dev; \
        popd
    - name: Save images with tar
      if: ${{ needs.setup.outputs.to_push == 'true' }}
      run: docker save ${{ needs.setup.outputs.dev_img_name }} > /tmp/dev_img.tar
    - name: Upload the dev image
      if: ${{ needs.setup.outputs.to_push == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: dev_img
        path: /tmp/dev_img.tar
  notify-line:
    runs-on: ubuntu-20.04
    needs: [setup, build-env-image, build-dev-image]
    if: ${{ needs.setup.outputs.enable_notify == 'true' && github.repository == 'falgon/roki-web' }}
    steps:
    - name: Notify LINE
      shell: bash
      env:
        API_ENDPOINT: https://notify-api.line.me/api/notify
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        ACTIONS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        curl -X POST $API_ENDPOINT \
          -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
          -d "message=roki.dev docker image build completed!%0a$ACTIONS_URL"
  push:
    runs-on: ubuntu-20.04
    needs: [setup, build-env-image, build-dev-image]
    if: ${{ needs.setup.outputs.to_push == 'true' && github.repository == 'falgon/roki-web' }}
    steps:
    - name: Download the env image
      uses: actions/download-artifact@v2
      with:
        name: env_img
        path: /tmp
    - name: Download the dev image
      uses: actions/download-artifact@v2
      with:
        name: dev_img
        path: /tmp
    - name: Load images
      shell: bash
      run: |
        docker load --input /tmp/env_img.tar
        docker load --input /tmp/dev_img.tar
    - name: Login GitHub Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u owner --password-stdin
    - name: Push to GitHub Package Registry
      shell: bash
      run: |
        docker tag ${{ needs.setup.outputs.env_img_name }} ${{ needs.setup.outputs.env_gh_registry }}
        docker tag ${{ needs.setup.outputs.dev_img_name }} ${{ needs.setup.outputs.dev_gh_registry }}
        docker push ${{ needs.setup.outputs.env_gh_registry }}
        docker push ${{ needs.setup.outputs.dev_gh_registry }}
